### ISSUE TITLE
Confirmation example needed

### ISSUE THREAD

**Issue by Alfred7** [LangZhai/ZLDialog#1]
The demo page: 

http://www.jqueryscript.net/demo/Tiny-Feature-rich-jQuery-Dialog-Popup-Plugin-ZLDialog/

does not contain a confirmation dialog (yes/no)

It would save everyone a lot of time if you were to provide one.

Thanks :-)

**Comment by LangZhai** [comment]
Thank you for your suggestion, but the Demo page not written by me, I have been going http://www.jqueryscript.net/other/Tiny-Feature-rich-jQuery-Dialog-Popup-Plugin-ZLDialog.html and leave a message, hope they can help me.

**Comment by LangZhai** [comment]
I've just added examples in the ReadMe.html for confirmation dialog box, thanks again for your suggestion.

**Comment by Alfred7** [comment]
Thank you LangZhai for your quick reply. I will try it out and let you know how it goes. :-)

I like your tool and that is why I am so keen to use it.

**Comment by Alfred7** [comment]
I went through your code and made the following very simple example:

var myDialog = $.dialog.confirm({
    content: "Do you want to continue?"}, 
        function () {
    $.dialog.message({
        content: "Yes",
                timeout:1000
    });
    myDialog();

}, function () { /*
    $.dialog.message({
        content: "No",
                timeout:1000
    }); */
        myDialog();
});

For English-speakers, the word "close" has a special meaning :-)
Thank you once more.

**Comment by LangZhai** [comment]
In fact, if you just want click the Cancel button to close the dialog box, you do not need the last function.

In addition, I found that English-speakers are having some trouble when using this plugin, Chinese-speakers in most cases do not need to change the title and button text, but English speakers do. So I'm thinking about how to improve the experience of non-Chinese.

I think this will be my focus for the next release.

**Comment by Alfred7** [comment]
Good idea. I wish I could program properly in Javascript.
